[account]
private_key = "YOURPRIVATEKEYHERE"
dry_run = false
simulate = false

[global]
mode = "Mint"
proxy_url = "YOURPROXYADDRESSES"
provider_url = "wss://eth-ws.721.gg"
flashbots_signer = ""
relays = [
    "https://relay.flashbots.net",
    "https://mev-relay.ethermine.org",
    "https://api.taichi.network:10001/rpc/public",
    "https://api.edennetwork.io/v1/bundle",
    "https://bundle.miningdao.io"
]

FULLCONFIGPASTE
